<h3>Messagerie</h3>

<div class="container">
    <div class="row">
        <div class="col-2">
            <table class="table table-hover">
                <tbody>
                    <?php
                    foreach ($convos as $conv)
                        display_conv($conv);
                    ?>
                </tbody>
            </table>
        </div>
        <div class="col-8">
            <div class="overflow-auto" style="height: 350px;">
                <?php
                if (!empty($_GET['id'])) {
                    if (!empty($msgs)) {
                        foreach ($msgs as $msg)
                            display_msg($msg);
                    } else
                        echo '<div class="text-center">Pas encore de messages !</div>';
                ?>
            </div>
            <div>
                <form action="" method="post">
                    <div class="row">
                        <div class="form-group">
                            <label class="form-label" for="message">Message</label>
                            <textarea class="form-control" id="message" name="message" cols="50" rows="5" placeholder="Tapez votre message"></textarea>
                        </div>
                    </div>
                    <button class="btn btn-primary" type="submit" name="envoyer">Envoyer</button>
                </form>
            <?php } else echo 'Lancez une conversation !' ?>
            </div>
        </div>
        <div class="col-2">
            <?php if (!empty($_GET)) { ?>
                <div class="card" style="width: 18rem;">
                    <img src="profilePictures/<?= $whoTo['profilePicture'] ?>" class="card-img-top img-fluid" alt="Image de profil">
                    <div class="card-body">
                        <h5 class="card-title"><?= $whoTo['firstName'], ' ', $whoTo['lastName'] ?></h5>
                        <p class="card-text"><?= $bio ?></p>
                        <a href="member.php?id=<?= $whoTo['id'] ?>" class="btn btn-primary">Consulter le profil</a>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
</div>